import json

def main():
    tab_mapping = {
        'dien-thoai-di-dong': 'Điện Thoại Di Động',
        'may-tinh-bang': 'Máy Tính Bảng',
        'laptop': 'Laptop',
        'may-tinh-de-ban-va-phu-kien': 'Máy Tính Để Bàn và Phụ Kiện',
        'am-thanh': 'Âm Thanh',
        'camera-giam-sat-2': 'Camera Giám Sát',
        'may-anh-may-quay-phim': 'Máy Ảnh, Máy Quay Phim',
        'may-quay-phim': 'Máy Quay Phim',
        'man-hinh-vi-tinh': 'Màn Hình Vi Tính',
        'man-hinh-may-in': 'Màn Hình Máy In',
        'dong-ho-thong-minh': 'Đồng Hồ Thông Minh',
        'dieu-khien-choi-game': 'Điều Khiển Chơi Game',
        'phu-kien-dien-thoai-may-tinh-bang': 'Phụ Kiện Điện Thoại, Máy Tính Bảng',
        'thiet-bi-thong-minh': 'Thiết Bị Thông Minh',
        'thiet-bi-so': 'Thiết Bị Số',
        'phu-kien-may-anh-may-quay-phim': 'Phụ Kiện Máy Ảnh, Máy Quay Phim',
        'phu-kien-may-bay-camera': 'Phụ Kiện Máy Bay, Camera',
        'thiet-bi-luu-tru-2': 'Thiết Bị Lưu Trữ',
        'phu-kien-may-vi-tinh': 'Phụ Kiện Máy Vi Tính',
        'linh-kien-may-tinh': 'Linh Kiện Máy Tính',
        'phu-kien-ong-kinh': 'Phụ Kiện Ống Kính',
        'thiet-bi-mang': 'Thiết Bị Mạng',
        'phu-kien-may-choi-game': 'Phụ Kiện Máy Chơi Game',
        'tv-video-am-thanh-thiet-bi-deo-cong-nghe': 'Tivi, Video, Âm Thanh, Thiết Bị Đeo Công Nghệ',
        'do-gia-dung-nho': 'Đồ Gia Dụng Nhỏ',
        'do-gia-dung-lon': 'Đồ Gia Dụng Lớn',
        'phu-kien-cho-tv': 'Phụ Kiện Cho TV',
        'cham-soc-da-mat': 'Chăm Sóc Da Mặt',
        'trang-diem': 'Trang Điểm',
        'dung-cu-cham-soc-sac-dep': 'Dụng Cụ Chăm Sóc Sắc Đẹp',
        'san-pham-tam-cham-soc-co-the': 'Sản Phẩm Tắm, Chăm Sóc Cơ Thể',
        'san-pham-cham-soc-toc': 'Sản Phẩm Chăm Sóc Tóc',
        'cham-soc-ca-nhan': 'Chăm Sóc Cá Nhân',
        'cham-soc-cho-nam-gioi': 'Chăm Sóc Cho Nam Giới',
        'nuoc-hoa': 'Nước Hoa',
        'thuc-pham-bo-sung': 'Thực Phẩm Bổ Sung',
        'thuc-pham-cho-sac-dep': 'Thực Phẩm Cho Sắc Đẹp',
        'ho-tro-tinh-duc': 'Hỗ Trợ Tình Dục',
        'thiet-bi-y-te': 'Thiết Bị Y Tế',
        'ta-dung-cu-ve-sinh': 'Tã & Dụng Cụ Vệ Sinh',
        'sua-cong-thuc-bot-an-dam': 'Sữa Công Thức & Bột Ăn Dặm',
        'quan-ao-phu-kien-cho-be': 'Quần Áo & Phụ Kiện Cho Bé',
        'do-dung-bu-sua-an-dam': 'Đồ Dùng Bú Sữa& Ăn Dặm',
        'xe-ghe-em-be': 'Xe & Ghế Em Bé',
        'cham-soc-tre-so-sinh-tre-nho': 'Chăm Sóc Trẻ Sơ Sinh & Trẻ Nhỏ',
        'tam-cham-soc-co-the-tre-so-sinh': 'Tắm & Chăm Sóc Cơ Thể Trẻ Sơ Sinh',
        'do-choi-tro-choi': 'Đồ Chơi & Trò Chơi',
        'xe-mo-hinh-tro-choi-dieu-khien-tu-xa': 'Xe Mô Hình & Trò Chơi Điều Khiển Từ Xa',
        'the-thao-tro-choi-ngoai-troi': 'Thể Thao & Trò Chơi Ngoài Trời',
        'do-choi-cho-tre-so-sinh-chap-chung': 'Đồ Chơi Cho Trẻ Sơ Sinh & Chập Chững',
        'do-choi-giao-duc-tre-em': 'Đồ Chơi Giáo Dục Trẻ Em',
        'bach-hoa-online-sua-uht-tiet-trung-sua-bot': 'Bách Hóa Online - Sữa UHT, Tiệt Trùng & Sữa Bột',
        'cac-loai-do-uong': 'Các Loại Đồ Uống',
        'shop-Thuc-pham-tu-sua-do-lanh': 'Shop Thực Phẩm Từ Sữa & Đồ Lạnh',
        'shop-do-hop': 'Shop Đồ Hộp',
        'shop-So-co-la-Snack-Keo': 'Shop Sô Cô La, Snack & Kẹo',
        'shop-Nguyen-lieu-nau-an-lam-banh': 'Shop Nguyên Liệu Nấu Ăn & Làm Bánh',
        'bach-hoa-online-chat-lau-chui-nha-cua': 'Bách Hóa Online - Chất Lau Chùi Nhà Cửa',
        'bach-hoa-online-muong-nia-nhua': 'Bách Hóa Online - Muỗng & Nĩa Nhựa',
        'bach-hoa-online-giat-ui': 'Bách Hóa Online - Giặt Ủi',
        'phu-kien-cho-thu-cung': 'Phụ Kiện Cho Thú Cưng',
        'thuc-an-thu-cung': 'Thức Ăn Thú Cưng',
        'shop-rau-cu-qua': 'Shop Rau Củ Quả',
        'do-dung-bep-phong-an': 'Đồ Dùng Bếp & Phòng Ăn',
        'tan-trang-nha-cua': 'Tân Trang Nhà Cửa',
        'dung-cu-dien': 'Dụng Cụ Điện',
        'dung-cu-cam-tay-da-nang': 'Dụng Cụ Cầm Tay Đa Năng',
        'do-dung-phong-ngu-gia-dinh': 'Đồ Dùng Phòng Ngủ & Gia Đình',
        'do-dung-phu-kien-phong-tam': 'Đồ Dùng & Phụ Kiện Phòng Tắm',
        'cac-loai-den': 'Các Loại Đèn',
        'san-pham-trang-tri-nha-cua': 'Sản Phẩm Trang Trí Nhà Cửa',
        'san-pham-noi-that': 'Sản Phẩm Nội Thất',
        'van-phong-pham-va-nghe-thu-cong': 'Văn Phòng Phẩm & Nghệ Thủ Công',
        'truyen-thong-am-nhac-sach': 'Truyền Thông, Âm Nhạc & Sách',
        'dung-cu-ve-sinh-2': 'Dụng Cụ Vệ Sinh',
        'trang-phuc-nu': 'Trang Phục Nữ',
        'giay-nu-thoi-trang': 'Giày Nữ Thời Trang',
        'do-ngu-noi-y': 'Đồ Ngủ & Nội Y',
        'phu-kien-cho-nu': 'Phụ Kiện Cho Nữ',
        'tui-cho-nu': 'Túi Cho Nữ',
        'trang-suc-nu': 'Trang Sức Nữ',
        'dong-ho-nu-thoi-trang': 'Đồng Hồ Nữ Thời Trang',
        'kinh-deo-mat-nu': 'Kính Đeo Mắt Nữ',
        'kinh-mat-danh-cho-nu': 'Kính Mắt Dành Cho Nữ',
        'trang-phuc-nam': 'Trang Phục Nam',
        'giay-nam-thoi-trang': 'Giày Nam Thời Trang',
        'do-lot-nam': 'Đồ Lót Nam',
        'phu-kien-thoi-trang-nam': 'Phụ Kiện Thời Trang Nam',
        'tui-nam': 'Túi Nam',
        'trang-suc-nam': 'Trang Sức Nam',
        'dong-ho-nam-gioi': 'Đồng Hồ Nam Giới',
        'kinh-deo-mat-nam': 'Kính Đeo Mắt Nam',
        'kinh-mat-danh-cho-nam': 'Kính Mát Dành Cho Nam',
        'trang-phuc-cua-be-trai': 'Trang Phục Của Bé Trai',
        'thoi-trang-giay-cho-be-trai': 'Thời Trang Giày Cho Bé Trai',
        'trang-phuc-cua-be-gai': 'Trang Phục Của Bé Gái',
        'thoi-trang-giay-danh-cho-be-gai': 'Thời Trang Giày Dành Cho Bé Gái',
        'tui-danh-cho-tre-em': 'Túi Dành Cho Trẻ Em',
        'dong-ho-danh-cho-tre-em': 'Đồng Hồ Dành Cho Trẻ Em',
        'kinh-mat-danh-cho-tre-em': 'Kính Mát Dành Cho Trẻ Em',
        'quan-ao-the-thao-be-gai': 'Quần Áo Thể Thao Bé Gái',
        'quan-ao-the-thao-be-trai': 'Quần Áo Thể Thao Bé Trai',
        'do-the-thao-cho-be-gai': 'Đồ Thể Thao Cho Bé Gái',
        'do-the-thao-cho-be-trai': 'Đồ Thể Thao Cho Bé Trai',
        'do-the-thao-nam': 'Đồ Thể Thao Nam',
        'quan-ao-the-thao-cho-nam': 'Quần Áo Thể Thao Cho Nam',
        'do-the-thao-nu': 'Đồ Thể Thao Nữ',
        'quan-ao-the-thao-cho-nu': 'Quần Áo Thể Thao Cho Nữ',
        'vali-ba-lo-tui-du-lich-2': 'Vali, Ba Lô & Túi Du Lịch',
        'hoat-dong-da-ngoai': 'Hoạt Động Dã Ngoại',
        'dung-cu-de-tap-the-hinh': 'Dụng Cụ Tập Thể Hình',
        'cac-mon-the-thao-vot': 'Các Môn Thể Thao Vợt',
        'cac-mon-tap-luyen-doi-khang': 'Các Môn Tập Luyện Đối Kháng',
        'dam-boc-vo-thuat-danh-mma': 'Đấm Bốc & Võ Thuật Dành Cho MMA',
        'cac-mon-the-thao-duoi-nuoc': 'Các Môn Thể Thao Dưới Nước',
        'phu-kien-the-thao': 'Phụ Kiện Thể Thao',
        'xe-mo-to-xe-tay-ga': 'Xe Mô Tô & Xe Tay Ga',
        'cham-soc-o-to': 'Chăm Sóc Ô Tô',
        'phu-kien-trong-o-to-xe-may': 'Phụ Kiện Trong Ô Tô & Xe Máy',
        'phu-kien-ngoai-o-to-xe-may': 'Phụ Kiện Ngoài Ô Tô & Xe Máy',
        'bo-phan-phu-tung-thay-the-cho-xe': 'Bộ Phận & Phụ Tùng Thay Thế Cho Xe',
        'hang-dien-tu-2': 'Hàng Điện Tử',
        'dau-nhot-o-to-xe-may': 'Dầu Nhớt Ô Tô & Xe Máy',
        'bo-phan-mo-to-phu-tung-thay-the-cho-mo-to': 'Bộ Phận Mô Tô & Phụ Tùng Thay Thế Cho Mô Tô',
        'do-bao-ho-mo-to': 'Đồ Bảo Hộ Mô Tô',
        'phu-kien-gan-ngoai-mo-to': 'Phụ Kiện Gắn Ngoài Mô Tô',
        'dau-nhot-mo-to': 'Dầu Nhớt Mô Tô',
        'banh-xe-lop-xe-may': 'Bánh Xe & Lốp Xe Máy',
        'mobilerecharge?wh_weex=true': 'Nạp Điện Thoại',
        'voucher-am-thuc': 'Voucher Ẩm Thực',
        'du-lich': 'Du Lịch',
        'hoat-dong-va-giai-tri': 'Hoạt Động & Giải Trí',
        'suc-khoe-va-lam-dep': 'Sức Khỏe & Làm Đẹp',
        'the-qua-tang': 'Thẻ Quà Tặng',
        'voucher-dich-vu': 'Voucher Dịch Vụ'
    }
    category_mapping = {
        'Electronic Devices': 'Thiết Bị Điện Tử',
        'Electronic Accessories': 'Phụ Kiện Điện Tử',
        'TV & Home Appliances': 'Tivi và Thiết Bị Gia Dụng',
        'Health & Beauty': 'Sức Khoẻ và Sắc Đẹp',
        'Babies & Toys': 'Trẻ Sơ Sinh và Đồ Chơi',
        'Groceries & Pets': 'Thực Phẩm và Thú Cưng',
        'Home & Lifestyle': 'Nhà Cửa và Phong Cách Sống',
        "Women's Fashion & Accessories": 'Thời Trang Nữ & Phụ Kiện',
        "Men's Fashion & Accessories": 'Thời Trang Nam & Phụ Kiện',
        'Sports & Travel': 'Thể Thao & Du Lịch',
        'Automotive & Motorcycles': 'Ô Tô & Xe Máy',
        'Digital Goods': 'Đồ Kỹ Thuật Số'
    }

    with open('lazada/merged_file.json', encoding='utf-8') as file:
        jsobj = json.load(file)

    for product in jsobj:
        product["category_name"] = category_mapping[product["category_name"]]
        product["tab_name"] = tab_mapping[product["tab_name"]]
        if product['itemSoldCntShow'] != "N/A":
            product['itemSoldCntShow'] = int(product['itemSoldCntShow'].split(' ')[0]) if 'K' not in product['itemSoldCntShow'].split(' ')[0] else int(float(product['itemSoldCntShow'].split(' ')[0][:-1]) * 1000)
        else:
            product['itemSoldCntShow'] = 0
        product['itemId'] = int(product['itemId'])
        product["priceShow"] = float(product["priceShow"])
        product["review"] = int(product["review"]) if product["review"] != '' else 0
        product["ratingScore"] = round(float(product["ratingScore"]), 1) if product["ratingScore"] != '' else 0

    with open('lazada/preprocess_data.json', 'w') as file:
        json.dump(jsobj, file)

    print('Done!')

if __name__ == '__main__':
    main()